### ISSUE TITLE
respec does not correctly highlight turtle examples

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#260] opened 2016-06-03 22:11 UTC
Respec does not correctly determine the type of the examples in the vocab.

For example, compare:
  http://w3c.github.io/web-annotation/vocab/wd/#specificresource
with the State example below it.

Not sure how to force respec to use a particular highlighter?

**Comment by iherman** [comment] 2016-06-04 07:01
I have run into similar issues in the selector note, and I switched off highlighting. The issue is that, I presume, Turtle is not on the recognized syntax list in respec, ie, the heuristic goes wrong...

@halindrome, @marcoscaceres, any other idea?

**Comment by azaroth42** [comment] 2016-06-04 18:43
Even if it could be made to highlight the examples consistently. It looks like the others are highlighting as CSS, which is better than nothing, I think.

**Comment by halindrome** [comment] 2016-06-04 18:47
We recently changed highlighting engines in ReSpec to highlight.js.  It
knows about A LOT of languages, but not, alas, turtle.  I imagine we could
make a plugin for turtle if you really wanted it.

On Sat, Jun 4, 2016 at 1:43 PM, Rob Sanderson notifications@github.com
wrote:

> Even if it could be made to highlight the examples consistently. It looks
> like the others are highlighting as CSS, which is better than nothing, I
> think.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/web-annotation/issues/260#issuecomment-223771362,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAfx8NZ-74Tf676FP9x9Rxviy_IW-TVmks5qIcc3gaJpZM4It8w7
> .

## 

Shane McCarron
halindrome@gmail.com

**Comment by azaroth42** [comment] 2016-06-04 18:48
Given the timing ... I'll write a script to syntax highlight with pygments and inject back before respec gets to the file.

Proposed highlighting scheme:
http://pygments.org/demo/5100827/

**Comment by halindrome** [comment] 2016-06-04 19:07
ok.   not really sure how that might work but I believe in you.

**Comment by azaroth42** [comment] 2016-06-04 19:30
Is there an option to tell respec not to try and highlight examples ever? Even without the highlight class on the node, it still injects a bunch of nonsense :(

**Comment by halindrome** [comment] 2016-06-04 19:39
A class of nohighlight on a block should mean leave it alone.  Is that what
you are trying?

On Sat, Jun 4, 2016 at 2:30 PM, Rob Sanderson notifications@github.com
wrote:

> Is there an option to tell respec not to try and highlight examples ever?
> Even without the highlight class on the node, it still injects a bunch of
> nonsense :(
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/web-annotation/issues/260#issuecomment-223773720,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAfx8KOn7UbRNRuaTtrdJ-wiyxWvgCtYks5qIdJkgaJpZM4It8w7
> .

## 

Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment] 2016-06-04 20:01
Also there is an overall ReSpec configuration option noHighlightCSS that, if true, will cause no highlighting at all to be done.  (That name is historic.)

**Comment by azaroth42** [comment] 2016-06-04 20:12
Check out: http://w3c.github.io/web-annotation/vocab/wd/index-respec.html

I think I have it mostly there -- errors lie in my python script, not in the respec HTML.

**Comment by halindrome** [comment] 2016-06-04 20:35
Looks good.  I was going to suggest you use whatever styles highlightjs
uses for the various types of components - so that colors etc remain
consistent. But this is good too!

On Sat, Jun 4, 2016 at 3:12 PM, Rob Sanderson notifications@github.com
wrote:

> Check out: http://w3c.github.io/web-annotation/vocab/wd/index-respec.html
> 
> I think I have it mostly there -- errors lie in my python script, not in
> the respec HTML.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/web-annotation/issues/260#issuecomment-223775846,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAfx8F7ONzDBty5iMJNYdoBGf7qsdoIwks5qIdxBgaJpZM4It8w7
> .

## 

Shane McCarron
halindrome@gmail.com

**Comment by iherman** [comment] 2016-06-05 07:37
@azaroth42 : can you put the exact command and parameters to do it on the repo? I think I should use the same style for the selector note (which has all the examples in turtle, too). Thx.

(I have pygments installed on my machine by now)

**Comment by azaroth42** [comment] 2016-06-05 21:03
It's now in the make_links script.  I'll pull out the syntax highlighting part and add it to the selector note directory for you.

**Comment by iherman** [comment] 2016-06-06 09:49
Not urgent. Can be dealt with after CR, it has, comparatively, a low priority!

**Comment by iherman** [comment] 2016-06-06 12:43
@azaroth42 : I actually did it: I copied and simplified the python file (had to install lxml on my machine) and it runs now. The effects are on the [index-respec.html](http://w3c.github.io/web-annotation/selector-note/index-respec.html) file.

Closing the issue.

**Closed as completed by iherman** 2016-06-06 12:43 UTC
Labels: vocab, editorial
