### ISSUE TITLE
Request header and language negotiation

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#220] opened 2016-05-17 12:56 UTC
[raised by r12a, not yet discussed by the i18n WG]

4.3.2 Request Header State
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#request-header-state

I'm trying to imagine how this works in the case of language negotiation. Say, for example, that the user was making annotations on
https://www.w3.org/International/questions/qa-site-conneg

This page is available in two languages: english and swedish. The page they'd actually be annotating may depend on a number of things. Possibilities include:

a. their browser preferences are set to request swedish versions, ie. Content-Language is set to 'sv', so they are working on the swedish page.

b. their browser preferences are still set to swedish, but the browser has stored information for that site (eg. via a cookie) to say that they prefer to read these pages in English, and so the english version is what they were looking at while annotating. Now the Content-Language information is incorrect if used to point another user to the target.

c. they may have originally gone to the swedish page, then followed a link to the english page.  Again, the Content-Language information is misleading.

I'm assuming that the implementation would supply the HTTP header information automatically, rather than the user having to provide that information (?).  If so, how does it determine what specific information to capture?  And can it record more than one HTTP request header (eg. the swedish pdf, rather than the english html, when all 4 combinations are available)?

Wouldn't the Content-Location in the receiving header be more useful?

Forgive me if i've misunderstood or failed to understand the HTTP headers adequately.

**Comment by iherman** [comment] 2016-05-17 15:29
This seems out of scope, the implementation of how to generate the HTTP state is not part of the spec...

**Comment by r12a** [comment] 2016-05-20 19:54
I'm not sure that all of the comments above are out of scope.  The spec says:

> it is important to be able to record the HTTP Request headers that need to be sent to retrieve the correct representation

But what i'm saying is that the **request** headers may not tally with what is actually delivered if the user is provided with another way to reach a specific version of a resource.  For example, language is an important aspect of content negotiation for sites with translated versions of the same resource, but the Accept-Language header is just an aspiration, it's the Content-Language **response** header that gives you more useful information about what version of the document was actually viewed.

**Comment by iherman** [comment] 2016-05-21 02:44
@r12a, that is all correct and o.k., but I do not think it is all that relevant for the particular item in this spec. 

You can regard 'State' (as well as Selectors) as some sort of fragment identifiers on steroids. Instead of having a very simple way of identifying a particular part of a resource (the `#...`) we try to add more. The State allows a certain level of control of the HTTP request when it is issued on the core URL. What can be controlled, in this sense, is what goes in the request header; that is what 'Request Header State' does. It is a one step control over the request, incomplete as it may be. (Note that there is a similar issue with the time version of state: the request may have information about the time range to request a particular version in time of a resource; there is no guarantee that the server can honour that request.)

While it is correct that the request header's state may not provide all the necessary information for language negotiations, there is _no_ claim that it does either. Some aspects may require the implementation, the particular usage, etc, to process the result further, but that _is_ out of scope at that point. For some usages a further refinement through, say, CSS selectors (or other) may be possible; I am not sure. But I maintain that this current issue is out of scope for this particular spec at this particular point. Hence the issue should remain closed.

(Note that handling the return header is not as easy as I would have thought. I learned at the F2F meeting that a JS script running in a browser has major difficulties getting hold of the response header. Sounds crazy, but there we are...)

**Comment by azaroth42** [comment] 2016-05-21 08:53
> Accept-Language header is just an aspiration, it's the Content-Language response header that gives you more useful information about what version of the document was actually viewed.

Further to @iherman, an implementation might record the value from Content-Language ... but that too might be insufficient, as it could be triggering the language detection from the initial client's IP address (which can't be reproduced, obviously), from the user agent, or from any number of other factors.  The best we can do is to **not** over specify exactly how the headers must be implemented, and instead provide a framework for clients to fill out information to the best of their ability, given perhaps out of band knowledge.  The most generic thing we can do is provide a way to record what request headers to send on the HTTP request for the resource... which is what Http Request State is.

If this is sufficient explanation, can we re-close the issue?

**Comment by r12a** [comment] 2016-05-23 12:52
Stepping back at bit, my actual concern here is that if i use the url https://www.w3.org/International/questions/qa-site-conneg and end up a the [swedish version of that article](https://www.w3.org/International/questions/qa-site-conneg.sv) and then start creating annotations, then the annotations need to indicate that the target is actually the swedish version of the content (otherwise, of course, the annotations may become unusable).  If that's possible in some way other than using the HTTP headers, then i don't imagine there is an issue here.

**Comment by iherman** [comment] 2016-05-23 13:04
> On 23 May 2016, at 14:52, r12a notifications@github.com wrote:
> 
> Stepping back at bit, my actual concern here is that if i use the url https://www.w3.org/International/questions/qa-site-conneg https://www.w3.org/International/questions/qa-site-conneg to navigate to the swedish version of that article https://www.w3.org/International/questions/qa-site-conneg.sv and then start creating annotations, then the annotations need to indicate that the target is actually the swedish version of the content (otherwise, of course, the annotations may become unusable). If that's possible in some way other than using the HTTP headers, then i don't imagine there is an issue here.

If the server behaves the way it should, ie, if I ask for a Swedish version via lang information in the HTTP header I do get a Swedish version, then this is solved by the HTTP state (which is stored as part of the annotation structure, so the system knows what is happening). If the server does not behave like that, then we cannot do it because we have no way to know, "in advance", that the resource is in Swedish and, frankly, I do not see any way to solve it with the current structures in the Anno model. (It may be a requirement for a version 2.)

**Comment by azaroth42** [comment] 2016-05-23 21:26
Even if the site uses 200 style conneg, it's behaving badly if it doesn't put the URI for .sv in to the Content-Location header.  If it doesn't, and the conneg is completely silent ... there's nothing we can do to get the content back anyway as it's basically just [cloaking](https://en.wikipedia.org/wiki/Cloaking).

**Comment by iherman** [comment] 2016-05-26 15:59
Discussed with the I18N WG on 2016-05-26, resolution is record, in a note, that clients may use the value of the Content-Location header to record the target of the annotation, to ensure that server specific content negotiation is taken into account (e.g. IP address geo-location, rather than Accept-Language header).

See also: http://www.w3.org/2016/05/26-i18n-irc#T15-58-46

**Closed as completed** 2016-06-03 15:48 UTC
Labels: i18n-tracker
