### ISSUE TITLE
Is fixing the list of fragment identifiers a good idea?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#40] opened 2015-06-25 11:02 UTC
I was re-reading the [fragment selector](http://www.w3.org/TR/annotation-model/#h4_fragment-selector) section in the model document; my reading is that the Recommendation would fix the fragment selectors that a conforming implementation can use.

I think this is a very bad idea. Fragment identifiers are defined all the time; by restricting the list to the fragment identifiers we know about at the time of publishing the specification we will incur the danger of being out of date very quickly and that would require updates of the Recommendation. At this moment we are already missing some on the list, like:
- fragment identifiers for CSV files, defined by rfc7111 (this is the open #26 issue on our issue list)
- fragment identifiers for EPUB files, called [CFI](http://www.idpf.org/epub/linking/cfi/epub-cfi.html)
- fragment identifiers for PDF, defined in the [PDF mime type registration](https://tools.ietf.org/html/rfc3778#section-3)

And these are only a few examples. Within W3C, actually, there is work on, eg., [Web packaging](http://www.w3.org/TR/web-packaging/) that may lead to new [fragment identifiers](http://www.w3.org/TR/web-packaging/#fragment-identifiers) defined for web packaging formats (and the publishing community _may_ come up with alternative for this), and we ourselves may define separate fragment identifiers for the RangeFinder API (as a serialization thereof). On long term we will loose.

I believe it would be a much better approach to leave this open ended. We should accept fragment identifiers that are officially defined either directly as part of a media type specification (as the one for PDF above) or as separate RFC-s (like rfc7111). I am sure there is a list somewhere maintained by IETF to refer to.

**Comment by BillKasdorf** [comment] 2015-06-25 14:23
+1

**Comment by jjett** [comment] 2015-06-25 14:35
+1

**Comment by paolociccarese** [comment] 2015-06-25 14:57
+1 seems the right thing to do.

On Thu, Jun 25, 2015 at 10:35 AM, Jacob notifications@github.com wrote:

> +1
> 
> On Thu, Jun 25, 2015 at 10:23 AM, BillKasdorf notifications@github.com
> wrote:
> 
> > +1
> > 
> > From: Ivan Herman [mailto:notifications@github.com]
> > Sent: Thursday, June 25, 2015 7:02 AM
> > To: w3c/web-annotation
> > Subject: [web-annotation] Is fixing the list of fragment identifiers a
> > good idea? (#40)
> > 
> > I was re-reading the fragment selector<
> > http://www.w3.org/TR/annotation-model/#h4_fragment-selector> section in
> > the model document; my reading is that the Recommendation would fix the
> > fragment selectors that a conforming implementation can use.
> > 
> > I think this is a very bad idea. Fragment identifiers are defined all the
> > time; by restricting the list to the fragment identifiers we know about
> > at
> > the time of publishing the specification we will incur the danger of
> > being
> > out of date very quickly and that would require updates of the
> > Recommendation. At this moment we are already missing some on the list,
> > like:
> > - fragment identifiers for CSV files, defined by rfc7111 (this is the
> >   open
> >   #26https://github.com/w3c/web-annotation/issues/26 issue on our issue
> >   list)
> > - fragment identifiers for EPUB files, called CFI<
> >   http://www.idpf.org/epub/linking/cfi/epub-cfi.html>
> > - fragment identifiers for PDF, defined in the PDF mime type
> >   registration<
> >   https://tools.ietf.org/html/rfc3778#section-3>
> > 
> > And these are only a few examples. Within W3C, actually, there is work
> > on,
> > eg., Web packaginghttp://www.w3.org/TR/web-packaging/ that may lead to
> > new fragment identifiers<
> > http://www.w3.org/TR/web-packaging/#fragment-identifiers> defined for
> > web
> > packaging formats (and the publishing community may come up with
> > alternative for this), and we ourselves may define separate fragment
> > identifiers for the RangeFinder API (as a serialization thereof). On long
> > term we will loose.
> > 
> > I believe it would be a much better approach to leave this open ended. We
> > should accept fragment identifiers that are officially defined either
> > directly as part of a media type specification (as the one for PDF above)
> > or as separate RFC-s (like rfc7111). I am sure there is a list somewhere
> > maintained by IETF to refer to.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/w3c/web-annotation/issues/40>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w3c_web-2Dannotation_issues_40-23issuecomment-2D115274690&d=AwMFaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=npggDwlZ6PziBzPBZthSo0f8iGOgRMf9ulO6o4WwfiA&m=5iKhJnAEaeL1dVrXZhwfmgnG7bY50SAWkTQe1YdvY48&s=nRk8wE2XKSOl2dUjXrgd6gOxYnYS6wvV3B4hJ8uv2qs&e=
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/web-annotation/issues/40#issuecomment-115277804.

## 

Dr. Paolo Ciccarese
Principal Knowledge and Software Engineer at PerkinElmer Innovation Lab
Assistant Professor in Neurology at Harvard Medical School

Assistant in Neuroscience at Mass General Hospital
ORCID: http://orcid.org/0000-0002-5156-2703

**Comment by azaroth42** [comment] 2015-06-25 14:58
+1 This seems familiar, so good to have an issue to make sure it happens!

**Comment by iherman** [comment] 2015-06-27 04:34
I have asked my contacts at IETF on whether there is an authoritative list of registered fragment identifiers and, alas!, there isn't any. Meaning that we will have to formulate this, if the issue is accepted, through some general hand-weaving...

**Comment by iherman** [comment] 2015-06-30 15:36
(There is a certain mess on where to have the discussion, github or mailing list. For the good order I copy Benjamin's comment here, originally [sent to the mailing list](http://www.w3.org/mid/CAE3H5FKtmz-dvuSOWrxztmFqWxKRs=eLOLR4w2B-gj5hr2P24Q@mail.gmail.com))

From: Benjamin Young 

Sorry to weigh in late on this...was out last week.

On Thu, Jun 25, 2015 at 7:02 AM, Ivan Herman via GitHub <sysbot+gh@w3.org> wrote:

> iherman has just created a new issue for
> https://github.com/w3c/web-annotation:
> 
> == Is fixing the list of fragment identifiers a good idea? ==
> I was re-reading the [fragment
> selector](http://www.w3.org/TR/annotation-model/#h4_fragment-selector)
>  section in the model document; my reading is that the Recommendation
> would fix the fragment selectors that a conforming implementation can
> use.

In what way does the spec limit the fragment selectors available? To me the prose reads pretty open handedly, but the list following doesn't state that it's non-normative or just there for examples.

For instance:
"The Web Annotation model defines a fragment-based Selector (oa:FragmentSelector) which allows both existing and future fragment specifications to be used to describe the segment of interest."

It seems that `dcterms:conformsTo` is included precisely to allow future fragment identifiers to be used as values of `oa:FragmentSelector`. It's even OK (though not recommended) for the URL stored as the target to include the fragement--in which case it would fall back to the URI spec, which in turn states that media type registrations (done at IANA) are the source of the meaning of fragments.

Perhaps the main action is to fix the text above the list, so it's clearly non-normative or just by way of example?

The prose doesn't seem to trip up my using RFC350349234 and it's new brain region fragment identifier. ;)

Thoughts?

**Comment by iherman** [comment] 2015-06-30 15:41
I did not mean to say that we have a very complicated issue here, but yes, the text seems to be misleading at best. It says

> URIs used to identify fragment specifications:

followed by a table, which really suggests that those in the table _are_ the URI-s that can be used. And yes, the solution may be as simple as just making it clear that those are some existing fragment ID-s, but others can also be used.

(B.t.w., we may want to get through the document to see if other tables, elsewhere in the document, can be interpreted in a restrictive manner.)

**Comment by BigBlueHat** [comment] 2015-06-30 16:50
Thanks for the repost @iherman.

How about changing that line to read:

> Examples of URIs used to identify fragment specifications:

That would have cleared it up for me.

It does seem to feel a bit strange to reference the specs--as they're just prose... Perhaps it's hoping for a better world where a machine can ask for the spec and Do The Right Thing after it "reads" it? :smiley: One can hope. :wink: 

Also, :+1: to going through all the table intros to be sure they're not implying something they shouldn't.

**Comment by fhirsch** [comment] 2015-07-06 19:36
+1

(It really helps to make specific proposals when raising or discussing issues, so thanks Benjamin)

**Comment by azaroth42** [comment] 2015-07-07 15:54
(Duplicate of #27)

**Comment by azaroth42** [comment] 2015-10-21 16:31
Resolved in Oct 2015 WD

**Closed as completed by azaroth42** 2015-10-21 16:31 UTC
Labels: model
