### ISSUE TITLE
(model) make definition of a character more precise

### ISSUE THREAD

**Issue by fsasaki** [w3c/web-annotation#209] opened 2016-05-09 11:53 UTC
From
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#embedded-textual-body 

> The character sequence of the content of the Textual Body: 

This text and the whole document is missing a definition of a character. Please consider to define that a character is a Unicode code point.

**Comment by azaroth42** [comment] 2016-05-18 09:03
Duplicate of 206, no?

**Comment by iherman** [comment] 2016-05-18 09:06
Referring to #206, closing this issue.

**Closed as completed by iherman** 2016-05-18 09:06 UTC
Labels: model, i18n-review
