### ISSUE TITLE
Language Literals not supported within the Body

### ISSUE THREAD

**Issue by hugomanguinhas** [w3c/web-annotation#149] opened 2016-02-08 14:32 UTC
At the moment, the only way to express the language of the text used as body of the annotation, is to create a Textual Body with a dc:language property referring to the language. There is also no way to add a language to a String Body (see 3.2.2.3).

A proposal would be to define oa:bodyText and oa:text as Language Literals according to the RDF spec, allowing for the Literal to be explicitly annotated with the language.

Pros:
- In line with the common practice for RDF.
- allow for text in multiple languages.
- the language becomes explicit and not implicit in the model.

Cons:
- an indirection (in JSON-LD) is needed for the text value and language.

Example 1: a case with a String Body tagged with language "en":

``` jsonld
{
  "motivation": "commenting",
  "bodyText": { "@value": "my useful comment", "@language": "en" },
  "target": "http://..."
}
```

Example 2: A Textual Body with a text written in English. In this situation, there was no need to create the Textual Body, only if for example a role was needed.

``` jsonld
{
  "motivation": "commenting",
  "body": {
    "@type": "TextualBody",
    "text": { "@value": "my useful comment", "@language": "en" }
  },
  "target": "http://..."
}
```

**Comment by iherman** [comment] 2016-02-08 15:25
> On 8 Feb 2016, at 15:41, Hugo Manguinhas notifications@github.com wrote:
> 
> At the moment, the only way to express the language of the text used as body of the annotation, is to create a Textual Body with a dc:language property referring to the language. There is also no way to add a language to a String Body (see 3.2.2.3).
> 
> A proposal would be to define oa:bodyText and oa:text as Language Literals according to the RDF spec, allowing for the Literal to be explicitly annotated with the language.
> 
> Pros:
> 
> In line with the common practice for RDF.
> allow for text in multiple languages.
> the language becomes explicit and not implicit in the model.
> Cons:
> 
> an indirection (in JSON-LD) is needed for the text value and language.
> Example 1: a case with a String Body tagged with language "en":
> 
> {
>   "motivation": "commenting",
>   "bodyText": { "@value": "my useful comment", "@language": "en" },
>   "target": "http://..."
> }
> Example 2: A Textual Body with a text written in English. In this situation, there was no need to create the Textual Body, only if for example a role was needed.
> 
> {
>   "motivation": "commenting",
>   "body": {
>     "@type": "TextualBody",
>     "text": { "@value": "my useful comment", "@language": "en" }
>   },
>   "target": "http://..."
> }

Actually, both examples are valid in JSON-LD as is, provided that the @context defines "bodyText" and "text" as a property whose value is a literal (which is the case). Ain't particularly pretty (and users are probably better advised to allow for language setting in their own @context if the language setting is overall). 

Really the only question is whether we introduce JSON friendly abbreviations for @value and @language. But, because that type of usage is really only important for very RDF centric applications, I am not sure it is worth doing it. As I said, it just works as is.

Ivan

**Comment by gsergiu** [comment] 2016-02-08 16:12
As feedback I saw that the Example 1 is marked as an issue 1 in String Body
https://www.w3.org/TR/annotation-model/#string-body

However this representation is in contradiction with the web annotation principles, which basically say that the annotation is: a body that is related to a target...
https://www.w3.org/TR/annotation-model/#web-annotation-principles

I agree with the simplication that in the case that the body is "only" a string, and no more information is available/required for the body, you can reduce the representation of the body to a string. 

Otherwise the TextualBody should be used as üresented in the Example 2. 

I don't think that is a good idea to introduce the  "bodyText" as replacement for a { body : {"@type" : "TextualBody"}

Of course different implementations may extend the context and implement this solution, but I would vote against making it normative, given the fact that the Example 2 (TextualBody) is already normative.

**Comment by hugomanguinhas** [comment] 2016-02-08 16:13
Hi Ivan,
I created this issued because I had the understanding while reading the spec that the use of RDF language tags was completely discouraged by the community.

I am particularly looking at this statement in section 3.2.2.3:

> There are several restrictions on when this form may be used and how it is to be interpreted. 
> The string body:
> ...
> - MUST NOT have a language associated with it.
> 
> ...

and if the following statement is correct:

> MUST BE an xsd:string and the data type must not be expressed in the serialization.

Than this means that the alternative that I have proposed is not allowed since in RDF, a Literal can have either a Language tag or a Datatype, but not both.

**Comment by gsergiu** [comment] 2016-02-08 16:21
my main concern is how to reprezent annotations in which the user is providing the same text in 2 languages?
example:
en: "my useful comment" <=> de: "mein nutzvoller Kommentar"

The current specifications would allow as to create 2 text bodies, however, in that case we loose the information that the meaning of the text is the same. 

One could also extend the model using the "@graph" construct, but I think that we should support i18n natively.

**Comment by azaroth42** [comment] 2016-02-08 16:51
Here's the number 1 reason why:

RDF does not allow for both language and data type to be associated with the same literal.  Thus you cannot have a string that is both text/plain and in English.  This is a critical requirement that language tagged strings cannot accomplish, and thus we have to work around it by mandating a TextualBody resource with predicates (dc:format and dc:language).

And the number 2 reason why:

Given number 1, we could still allow language tagged strings... but that would be very confusing, especially as there would be both type (rdf:type) and @type (data type of the literal), value (rdfs:value) and @value (the value of a literal), and language (dc:language) and @language (the language tag of the literal).  Also, it would be inconsistent between @type (literal) and format (resource) as to where to put the data type.

Pros:
- Common practice for RDF -- Isn't our primary focus.  We aim for compatibility and following best practices where possible, but not at the expense of ease of understanding and implementation.
- Allow multiple languages -- Is a big concern, and one that is addressed already with Choice + TextualBody with dc:language.  It is explicit that it is a choice between two comparable resources, and not simply two different bodies.
- Language is explicit -- I think that it is explicit already. It's associated with the resource, not the literal.

In the unpublished working draft we moved away from overloading body, and explicitly added bodyText, see: http://w3c.github.io/web-annotation/model/wd2/#string-body

**Comment by azaroth42** [comment] 2016-02-08 16:52
(And logistically, I propose close wontfix when @gsergiu and @hugomanguinhas are satisfied with the response)

**Comment by gsergiu** [comment] 2016-02-08 18:20
Hi @azaroth42 

Well.. for the multilinguality/i18n problem the concept of using a choice construct seems ok for me, still incomplete.

With this regard I have additional questions:
1. Why if the user uses simple texts and not resourced that have an id/URI?
the current definition says: "A Choice has an ordered list of resources"
And the annotation from the example is basically made to link the two previously created resources.

In my example I just wanted to post a comment (in something like twitter) 
"Happy New Year"@en/"Froehes Neues Jahr"@de/"La multi ani"@ro and I would like that my romanian friend see the text deplayed in romanian, the austrian ones in german and the rest in english...

Yes, it looks like a choise but with embedded text.
1. Moreover I would like to define a default choice, and probalby also with a preffered choice (e.g. I have some friends that understand both german and romanian)
   Prefered & Default choice would be very useful for decinding which text to display in the frontend.
2. Is this the way chose to represent the "SemanticTags"? Because for these tags we would like to store the text of "skos:prefferedLabels" within the annotations, becasue I don't want to send 2 or more queries in order to be able to display an annotation (i.e. one for annotation & one for retrieving the labels in all langagues).

**Comment by azaroth42** [comment] 2016-02-08 19:15
1.  That's not possible. You have to use TextualBody resources in a Choice. That TextualBody can have a language associated with it.
2.  The preferred or default option is the first in the list, hence having order.
3.  I don't see what the issue is here? You can add skos:preferredLabel to a resource, no?

**Comment by iherman** [comment] 2016-02-09 07:39
> In my example I just wanted to post a comment (in something like twitter) 
> "Happy New Year"@en/"Froehes Neues Jahr"@de/"La multi ani"@ro https://github.com/ro and I would like that my romanian friend see the text deplayed in romanian, the austrian ones in german and the rest in english...

This is the approach I would be pretty much opposed to, sorry. Introducing such a microsyntax means that an Annotation cannot be handled by a standard JSON, or JSON-LD tool. 

Actually, the proposed syntax is not acceptable JSON. It should be something like

"property" : "'Happy New Year'@en"

which is especially ugly. Even if we accept this, 
- If I forget about RDF, the current approach works well for pure JSON tools and users.
- If I add RDF, the standard conversion from JSON-LD to RDF would be erroneous, it would generate "'Happy New Year'@en"^^xsd:string, which is of course valid RDF but not what you would expect. Meaning that the JSON-LD to RDF conversion should be adapted for annotations

**Comment by iherman** [comment] 2016-02-12 16:32
Decision to close it without further action at telco on 2016-02-12

See http://www.w3.org/2016/02/12-annotation-irc#T16-32-26

**Closed as completed by iherman** 2016-02-12 16:32 UTC
Labels: model

**Comment by gsergiu** [comment] 2016-02-12 20:12
@iherman 
:( I'm sorry to hear that this was decision. I was tracked with some more important work in these days and I couldn't answer your last comment. But I will still answer it now .. at least for documentation.

Of corse the provided example is not valid json. I just wanted to "pseudo encode" the information that is expected to be provided by the user.

If it is about how would I encode the information, I would propose this format:
"body": { 
  "@type": "TextualBody", 
  "text": [
    { "@value": "Happy New Year", "@language": "en" }
    { "@value": "Froehes Neues Jahr", "@language": "de" }
    { "@value": "La multi ani", "@language": "ro" }
  ] 
 }

The question is if this is the appropriate format for automatic conversion to RDF/XML in something like
oa:hasBody [
        a oa:TextualBody;
        oa:text [
            "Happy New Year"@en;
            "Froehes Neues Jahr"@de;
            "La multi ani"@ro
        ];  
    ] .
(I'm not an expert of turtle format .. so please feel free to correct the turtle representation)

**Comment by gsergiu** [comment] 2016-02-12 20:25
@azaroth42 
1. I do agree that the default and preffered languages in this context is more related to the expected behaviour on the clientside. So ... more related to #113 (and we can separate it for now form the multilingual problem)
2. Given that the upper example would be a resource: http:/mydomain.com/happy_new_year.
   Would it be valid something like this?
   "body": {
   "@id": "http:/mydomain.com/happy_new_year",
   "prefLabel": [
   { "@value": "Happy New Year", "@language": "en" }
   { "@value": "Froehes Neues Jahr", "@language": "de" }
   { "@value": "La multi ani", "@language": "ro" }
   ] 
   },
   PS: this is our main requirement to embedd the multilingual texts related to the resource in the annotation body, so that we can show the text to the users and not the URLs.

**Comment by gsergiu** [comment] 2016-02-12 20:50
PS: the skos concepts are supported through the context and they are referenced in the draft proposal only in the diagram explaining the mechanisms of extending the motivation types. However, there is no jsonld example about how to use the skos concepts in the annotations.

**Comment by iherman** [comment] 2016-02-13 08:31
@gsergiu, as I already commented, I believe that, from a JSON-LD point of view, your examples are correct JSON-LD and will be translated into Turtle (the turtle representation is slightly different, but that is side issue). Ie, RDF oriented applications may do that without further ado.

However, it is another question whether that would be THE approach included by the model to express languages. Repeating the argument in the thread, the consensus is that the approach based on dc, ie, shown in:

https://w3c.github.io/web-annotation/model/wd/#h-textual-body https://w3c.github.io/web-annotation/model/wd/#h-textual-body

is more natural for JSON users, and is in line with the usual practice or relying on the dublin core terminology. It makes the result slightly more convoluted from a pure RDF point of view insofar as it does not make use of the language tagged literals of RDF, and introducing in the model two different ways of expressing, essentially, the same information is not a good idea.

**Comment by gsergiu** [comment] 2016-02-13 23:01
@iherman 
1. Yes ... this is also our question which approach should be used to embed multilingual texts in the annotation body? The current examples include only "mono"-lingual texts, and this is not enough for our usecase. We aim at being compliant with the standard, and we want to avoid extending the context.
2.   If I got it right with dc language you mean using “language”, instead of “@language”. Well ... that is not that much the problem from my point of view.  However by taking a look in the string-internationalization, in the json-ld, I saw first that the section is non-normative, and secondly I saw that in examples there are several different way to embed “language-maps”. 
   https://www.w3.org/TR/json-ld/#string-internationalization
   a)  Example 31 is actually monolingual.  
   b)  Example 32 is only bilingual , in the sense the it uses “ja” or “null”.  I also don’t like the idea to use embedded “@context” elements for resetting the language.
   c)  Example 33, seems to be the one that is very close to the “text@language” format used in turtle. But again this overloads massively the context, and more than that for every multilingual field. That’s a total no go from my side.
   d)   Example 34 is the most natural and compact representation for end users. However, this still requires to add "@container": "@language" in the context (for the “text” property I assume)
   e)  Example 35 and 36 are exactly the representations discussed in the previous comments in this thread...  
   So ... by looking as these options,  I think that the question is still open. Which should be the preffered solution?
3. I think that in the context of Web (& annotations) the String internationalization is very important and I would be glad if the WA standard proposes a normative solution for it. Don’t you agree on this?

**Comment by hugomanguinhas** [comment] 2016-02-17 14:35
Hi Rob, Ivan and Sergiu,

Like Sergiu, I was a bit surprised to see this issue being closed so quickly especially given that we did not have sufficient time to respond and discuss this in more detail.

Responding to Rob’s initial comments:

> Common practice for RDF -- Isn't our primary focus. We aim for compatibility and following best practices where possible, but not at the expense of ease of understanding and implementation.

I understand and agree, but see next comments...

> Allow multiple languages -- Is a big concern, and one that is addressed already with Choice + TextualBody with dc:language. It is explicit that it is a choice between two comparable resources, and not simply two different bodies.

I don’t see how having a Choice with multiple Textual Bodies each of them with a dc:language will help make it “easier to understand and to implement”, especially since JSON-LD allows you to have language-map to represent literals in multiple languages… what could be easier? Also, conceptually, there is nothing saying that all choices are closely related, in this case representing multiple facets of the same thing.

> Language is explicit -- I think that it is explicit already. It's associated with the resource, not the literal.

This is where I feel lies the biggest problem... as you mentioned the dc:language is meant to sate the language of the resource (and not the language of the metadata describing the resource). So, in this case, what is the resource?

**Comment by hugomanguinhas** [comment] 2016-02-17 14:49
Hi all,

A question that I am starting to realize from Rob's comments and some discussions around Choices in the Body:

Is the Web Annotation Data Model really intend to be "a structured model and format to enable annotations to be shared and reused across different hardware and software platforms", or is it intend to represent a specific view over an annotation, with particular interest on how it should be interpreted by a client application and displayed to a user?

... much like the role of the IIIF Presentation API, over e.g. a archival or cataloguing system.

**Comment by azaroth42** [comment] 2016-02-17 19:13
It's a non issue, sorry. There's no solution for the challenges with RDF that I already outlined:

> RDF does not allow for both language and data type to be associated with the same literal. Thus you cannot have a string that is both text/plain and in English. This is a critical requirement that language tagged strings cannot accomplish, and thus we have to work around it by mandating a TextualBody resource with predicates (dc:format and dc:language).
> 
> Given number 1, we could still allow language tagged strings... but that would be very confusing, especially as there would be both type (rdf:type) and @type (data type of the literal), value (rdfs:value) and @value (the value of a literal), and language (dc:language) and @language (the language tag of the literal). Also, it would be inconsistent between @type (literal) and format (resource) as to where to put the data type.

So language maps don't help.  And yes, the options of a choice are all ... options of a choice.  You pick one of them. What other requirements are there that aren't supported?  There's no use case or requirement to say how closely related the options are or not. If you have one, please describe it.

The resource is the body ... as per the issue. The language of the resource is thus the language of the body resource ... there is no metadata here.

**Comment by azaroth42** [comment] 2016-02-17 19:16
Regarding prefLabel ... we don't have a recommendation for associating labels with bodies.  You can do whatever you want, as descriptive metadata of arbitrary resources is well outside of this WG's scope.
